---
engines:
  brakeman:
    enabled: true
    exclude_fingerprints:
      - 6ad4464dbb2a999591c7be8346dc137c3372b280f4a8b0c024fef91dfebeeb83
  duplication:
    enabled: true
    exclude_fingerprints:
      - 3e30de88eb9d993e74c31d0309e13f7c
      - 3fe527befeb3a1f8ac773f6393f75e0c
      - 8173dcc032219344176991b7bafa15a6
      - 8a7dae1e94950e59319a7cd259732bb4
      - 941c94b2e2f00eee9dcceb7a1faeb92f
      - 93db286dbc27996f277d7246f80afd8a
      - 5b45a0b1e0e92099ae4725fdbfb8fd3f
    config:
      languages:
      - ruby
      - javascript
  eslint:
    enabled: true
    config:
      extensions:
        - .es6
  fixme:
    enabled: true
  rubocop:
    enabled: true
  coffeelint:
    enabled: true
ratings:
  paths:
  - Gemfile.lock
  - "**.erb"
  - "**.rb"
  - "**.js"
  - "**.es6"
  - "**.coffee"
  - "**.rake"
  - "**.scss"
exclude_paths:
- config/
- db/
- spec/
- vendor/
