---
engines:
  brakeman:
    enabled: true
    exclude_fingerprints:
      - 6ad4464dbb2a999591c7be8346dc137c3372b280f4a8b0c024fef91dfebeeb83
  duplication:
    enabled: true
    exclude_fingerprints:
      - 3e30de88eb9d993e74c31d0309e13f7c
      - 8173dcc032219344176991b7bafa15a6
    config:
      languages:
      - ruby
      - javascript
  eslint:
    enabled: true
    config:
      extensions:
        - .es6
  fixme:
    enabled: true
  rubocop:
    enabled: true
  coffeelint:
    enabled: true
  scss-lint:
    enabled: true
    checks:
      Comment:
        enabled: false
      StringQuotes:
        enabled: false
      SelectorFormat:
        enabled: false
      EmptyLineBetweenBlocks:
        enabled: false
      PropertySortOrder:
        enabled: false
      PlaceholderInExtend:
        enabled: false
      VendorPrefix:
        enabled: false
ratings:
  paths:
  - Gemfile.lock
  - "**.erb"
  - "**.rb"
  - "**.js"
  - "**.es6"
  - "**.coffee"
  - "**.rake"
  - "**.scss"
exclude_paths:
- config/
- db/
- spec/
- vendor/
