require: rubocop-rspec

Metrics/CyclomaticComplexity:
  Exclude:
    - 'app/services/sufia/file_set_audit_service.rb'
    - 'lib/sufia/arkivo/metadata_munger.rb'

Metrics/PerceivedComplexity:
  Exclude:
    - 'app/services/sufia/file_set_audit_service.rb'

Metrics/ClassLength:
  Exclude:
    - 'lib/generators/sufia/templates/catalog_controller.rb'
    - 'lib/generators/sufia/install_generator.rb'
    - 'lib/sufia/configuration.rb'
    - 'app/services/sufia/user_stat_importer.rb'

Metrics/ParameterLists:
  Exclude:
    - 'app/jobs/batch_create_job.rb'

Metrics/AbcSize:
  Exclude:
    - 'app/controllers/concerns/sufia/admin/depositor_stats.rb'
    - 'app/controllers/concerns/sufia/my_controller_behavior.rb'
    - 'app/services/sufia/user_stat_importer.rb'
    - 'app/services/sufia/workflow/permission_query.rb'
    - 'lib/sufia/arkivo/metadata_munger.rb'

Metrics/ModuleLength:
  Exclude:
    - 'app/controllers/concerns/sufia/curation_concern_controller.rb'
    - 'app/controllers/concerns/sufia/collections_controller_behavior.rb'
    - 'app/controllers/concerns/sufia/users_controller_behavior.rb'
    - 'app/helpers/sufia/sufia_helper_behavior.rb'
    - 'app/models/concerns/sufia/solr_document_behavior.rb'
    - 'app/services/sufia/workflow/permission_query.rb'
    - 'spec/services/sufia/workflow/permission_query_spec.rb'

Metrics/MethodLength:
  Exclude:
    - 'app/controllers/concerns/sufia/curation_concern_controller.rb'
    - 'app/controllers/concerns/sufia/my_controller_behavior.rb'
    - 'app/helpers/sufia/citations_behaviors/formatters/endnote_formatter.rb'
    - 'app/models/concerns/sufia/file_set/derivatives.rb'
    - 'app/models/concerns/sufia/solr_document/export.rb'
    - 'app/services/sufia/workflow/permission_query.rb'
    - 'lib/generators/sufia/templates/migrations/create_local_authorities.rb'
    - 'lib/generators/sufia/install_generator.rb'
    - 'lib/sufia/arkivo/metadata_munger.rb'
    - 'lib/sufia/configuration.rb'
    - 'lib/sufia/rails/routes.rb'
    - 'spec/support/*'



Style/LineEndConcatenation:
  Exclude:
    - 'spec/test_app_templates/lib/generators/**/*'
    - 'lib/generators/**/*'

Style/PredicateName:
  Exclude:
    - 'app/helpers/sufia/sufia_helper_behavior.rb'

Rails/Output:
  Exclude:
    - 'lib/generators/**/*'

Rails/HasAndBelongsToMany:
  Exclude:
    - 'app/models/domain_term.rb'
    - 'app/models/local_authority.rb'

RSpec/NamedSubject:
  Enabled: false

RSpec/ExampleLength:
  Max: 7
  Exclude:
    - 'spec/controllers/api/items_controller_spec.rb'
    - 'spec/controllers/authorities_controller_spec.rb'
    - 'spec/controllers/collections_controller_spec.rb'
    - 'spec/controllers/curation_concerns/file_sets_controller_spec.rb'
    - 'spec/controllers/my/highlights_controller_spec.rb'
    - 'spec/controllers/curation_concerns/generic_works_controller_spec.rb'
    - 'spec/controllers/stats_controller_spec.rb'
    - 'spec/controllers/sufia/batch_uploads_controller_spec.rb'
    - 'spec/controllers/transfers_controller_spec.rb'
    - 'spec/controllers/users_controller_spec.rb'
    - 'spec/forms/sufia/forms/collection_form_spec.rb'
    - 'spec/forms/sufia/forms/batch_edit_form_spec.rb'
    - 'spec/forms/sufia/forms/batch_upload_form_spec.rb'
    - 'spec/features/**/*'
    - 'spec/helpers/sufia_helper_spec.rb'
    - 'spec/helpers/dashboard_helper_spec.rb'
    - 'spec/javascripts/jasmine_spec.rb'
    - 'spec/jobs/file_set_attached_event_job_spec.rb'
    - 'spec/jobs/content_update_event_job_spec.rb'
    - 'spec/jobs/content_restored_version_event_job_spec.rb'
    - 'spec/jobs/content_new_version_event_job_spec.rb'
    - 'spec/jobs/content_depositor_change_event_job_spec.rb'
    - 'spec/jobs/content_deposit_event_job_spec.rb'
    - 'spec/jobs/content_delete_event_job_spec.rb'
    - 'spec/lib/sufia/resource_sync/capability_list_writer_spec.rb'
    - 'spec/models/generic_work_spec.rb'
    - 'spec/models/featured_work_spec.rb'
    - 'spec/services/sufia/actor_factory_spec.rb'
    - 'spec/services/sufia/user_stat_importer_spec.rb'
    - 'spec/views/catalog/_index_list_default.html.erb_spec.rb'
    - 'spec/views/collections/_form.html.erb_spec.rb'

RSpec/VerifiedDoubles:
  Enabled: false

RSpec/AnyInstance:
  Exclude:
    - 'spec/controllers/sufia/admin/admin_sets_controller_spec.rb'
    - 'spec/controllers/api/items_controller_spec.rb'
    - 'spec/controllers/api/zotero_controller_spec.rb'
    - 'spec/controllers/batch_edits_controller_spec.rb'
    - 'spec/controllers/collections_controller_spec.rb'
    - 'spec/controllers/dashboard_controller_spec.rb'
    - 'spec/controllers/downloads_controller_spec.rb'
    - 'spec/controllers/mailbox_controller_spec.rb'
    - 'spec/controllers/stats_controller_spec.rb'
    - 'spec/controllers/curation_concerns/file_sets_controller_spec.rb'
    - 'spec/controllers/users_controller_spec.rb'
    - 'spec/controllers/transfers_controller_spec.rb'
    - 'spec/jobs/file_set_attached_event_job_spec.rb'
    - 'spec/jobs/content_update_event_job_spec.rb'
    - 'spec/jobs/content_restored_version_event_job_spec.rb'
    - 'spec/jobs/content_new_version_event_job_spec.rb'
    - 'spec/jobs/content_depositor_change_event_job_spec.rb'
    - 'spec/jobs/content_deposit_event_job_spec.rb'
    - 'spec/lib/sufia/arkivo/create_subscription_job_spec.rb'
    - 'spec/lib/sufia/arkivo/actor_spec.rb'
    - 'spec/presenters/sufia/work_usage_spec.rb'
    - 'spec/presenters/sufia/file_usage_spec.rb'
    - 'spec/services/sufia/repository_audit_service_spec.rb'
    - 'spec/services/sufia/workflow/permission_generator_spec.rb'
    - 'spec/services/sufia/workflow/sipity_actions_generator_spec.rb'
    - 'spec/services/sufia/workflow/state_machine_generator_spec.rb'
    - 'spec/services/sufia/workflow/workflow_permissions_generator_spec.rb'
