language: ruby
before_install:
  - sudo apt-get install libclamav-dev clamav-data clamav-daemon
  - sudo freshclam -v
rvm:
  - "2.0.0"
  - "2.1.0-preview2"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
notifications:
  email:
    recipients:
      - "ul-dlt-hydra@lists.psu.edu"
    on_success: "change"
    on_failure: "always"
  irc:
    channels:
      - "irc.freenode.org#scholarsphere"
      - "irc.freenode.org#projecthydra"
    template:
      - "%{repository}//%{branch}@%{commit} by %{author}: %{message} - %{build_url}"
services:
  - redis-server
